import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm")
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap") }
}

dependencies {
    implementation("io.ktor:ktor-server-core-jvm:2.0.1")
    implementation("io.ktor:ktor-client-core:2.0.1")
    implementation("io.ktor:ktor-client-cio:2.0.1")
    implementation("io.ktor:ktor-serialization-jackson:2.0.1")
    implementation("org.litote.kmongo:kmongo-coroutine:4.6.0")
    // https://mvnrepository.com/artifact/io.mockk/mockk
    testImplementation("io.mockk:mockk:1.12.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.21")
    implementation ("org.jetbrains.exposed:exposed-core:0.38.2")
    implementation ("org.jetbrains.exposed:exposed-dao:0.38.2")
    implementation ("org.jetbrains.exposed:exposed-jdbc:0.38.2")
    implementation ("org.postgresql:postgresql:42.3.3")
    implementation ("com.zaxxer:HikariCP:5.0.1")
    implementation("org.apache.kafka:kafka-clients:3.1.0")
    implementation("io.ktor:ktor-server-core:2.0.2")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(11))
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = 11.toString()
    }
}
